(tests
 (names
  test_level
  test_value
  test_entry
  test_context
  test_logger
  test_formatter
  test_output
  test_log_exn)
 (libraries olog alcotest eio_main yojson unix))

(test
 (name test_ppx)
 (libraries olog alcotest eio_main)
 (preprocess
  (pps olog_ppx)))

(executable
 (name run_ppx_driver)
 (modules run_ppx_driver)
 (libraries ppxlib olog_ppx))

(cram
 (deps run_ppx_driver.exe))
